---
- name: "Debug os default templates"
  ansible.builtin.debug:
    var: "{{ item }}"
  loop: "{{ [foreman_os_default_templates, foreman_custom_os_default_templates | default([{}])] |
            community.general.lists_mergeby('name',
                                            recursive=true,
                                            list_merge='prepend_rp') }}"
  loop_control:
    label: "{{ item.name }}"
  when: foreman_debug

- name: "Create default OS template (fail in check mode)"
  theforeman.foreman.os_default_template:
    operatingsystem: "{{ item.operatingsystem | mandatory }}"
    template_kind: "{{ item.template_kind | mandatory }}"
    provisioning_template: "{{ item.provisioning_template | default(omit)}}"
    state: "{{ item.state | default('present') }}"
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_validate_certs | default('true') }}"
  loop: "{{ [foreman_os_default_templates, foreman_custom_os_default_templates | default([{}])] |
            community.general.lists_mergeby('name',
                                            recursive=true,
                                            list_merge='prepend_rp') }}"
  loop_control:
    label: "{{ item.name }}"
  ignore_errors: "{{ ansible_check_mode }}"
