---
- name: "Debug subnets config"
  ansible.builtin.debug:
    var: item
  loop: "{{ foreman_subnets | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: foreman_debug

- name: Setup subnets
  theforeman.foreman.subnet:
    name: "{{ item.name | default(location) }}"
    description: "{{ item.description | default('mgmt net') }}"
    network: "{{ item.network | mandatory }}"
    cidr: "{{ item.cidr | mandatory }}"
    mask: "{{ item.mask | mandatory }}"
    gateway: "{{ item.gateway | default(omit) }}"
    dns_primary: "{{ item.dns_primary | default(omit) }}"
    dns_secondary: "{{ item.dns_secondary | default(omit) }}"
    boot_mode: "{{ item.boot_mode | default('DHCP') }}"
    dhcp_proxy: "{{ item.dhcp_proxy | default(omit) }}"
    tftp_proxy: "{{ item.tftp_proxy | default(omit) }}"
    httpboot_proxy: "{{ item.httpboot_proxy | default(omit) }}"
    ipam: "{{ item.ipam | default('DHCP') }}"
    domains: "{{ item.domains | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_validate_certs | default('true') }}"
  loop: "{{ foreman_subnets | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
