---
# Either add your own templates via setting foreman_provisioning_template
# or autoload all the templates (provisioning and snippet) in files/

- name: "Debug provisoning template config"
  ansible.builtin.debug:
    var: item
  loop: "{{ foreman_provisioning_template | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: foreman_debug

- name: Setup provisioning templates
  theforeman.foreman.provisioning_template:
    name: "{{ item.name }}"
    template: "{{ item.template | default(omit) }}"
    file_name: "{{ item.file_name | default(omit) }}"
    operatingsystems: "{{ item.operatingsystems | default(omit) }}"
    kind: "{{ item.kind | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_validate_certs | default('true') }}"
  loop: "{{ foreman_provisioning_templates | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: not foreman_use_upstream_templates
  ignore_errors: "{{ ansible_check_mode }}"

- name: Fetch upstream provisioning templates
  theforeman.foreman.provisioning_template:
    name: "{{ item.name }}"
    template: "{{ lookup('ansible.builtin.url', foreman_upstream_template_url + item.kind + '/' + item.file_name, split_lines=False) }}"
    operatingsystems: "{{ item.operatingsystems | default(omit) }}"
    kind: "{{ item.kind | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_validate_certs | default('true') }}"
  loop: "{{ foreman_provisioning_templates | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: foreman_use_upstream_templates
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Autoload all provisioning templates"
  theforeman.foreman.provisioning_template:
    template: '{{ lookup("file", item) }}'
    operatingsystems: "{{ ('provisioning_templates' in item) | ternary([el7_latest, el8_latest, el9_latest], omit) }}"
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    validate_certs: "{{ foreman_validate_certs | default('true') }}"
  with_fileglob:
    - "files/provisioning_templates/*.erb"
    - "files/snippet/*.erb"
  when: foreman_autoload_templates
  ignore_errors: "{{ ansible_check_mode }}"
